vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd@0.1.9:RqXwspHjd7liDzeASuaexQ==
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==
    - vincaslt.highlight-matching-tag@0.10.0:pP+bZ1YdLRE3UArege6hTw==